# Generated by Django 5.1.5 on 2025-02-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('genre', models.CharField(choices=[('D', 'Drama'), ('C', 'Comedia'), ('AV', 'Aventura'), ('CF', 'Ciencia ficción'), ('AC', 'Acción'), ('T', 'Terror')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('picture', models.ImageField(upload_to='catalogo_images')),
            ],
        ),
        migrations.CreateModel(
            name='VHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('type', models.CharField(choices=[('A', 'Audible'), ('D', 'Documental'), ('P', 'Película'), ('M', 'Música')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('picture', models.ImageField(upload_to='catalogo_images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('picture', models.ImageField(upload_to='catalogo_images')),
            ],
        ),
    ]
