# Generated by Django 5.1.5 on 2025-02-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='pokemon_images')),
            ],
        ),
        migrations.CreateModel(
            name='VHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='pokemon_images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='pokemon_images')),
            ],
        ),
    ]
